version: '3'
services:
  mysqldb:
    image: mysql:5.6
    container_name: container-invillia-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: invilliaDB
      MYSQL_USER: invillia
      MYSQL_PASSWORD: invillia